mingw: Package debug files
When building on f18, the build fails because of unpackaged
debug files. Use the appropriate mingw macro to generate
the mingw debug packages.

The build failure is:

RPM build errors:
error: Installed (but unpackaged) file(s) found:
   /usr/i686-w64-mingw32/sys-root/mingw/bin/debug-helper.exe.debug
   /usr/i686-w64-mingw32/sys-root/mingw/bin/remote-viewer.exe.debug
   /usr/i686-w64-mingw32/sys-root/mingw/bin/virt-viewer.exe.debug
   /usr/i686-w64-mingw32/sys-root/mingw/bin/windows-cmdline-wrapper.exe.debug
   /usr/x86_64-w64-mingw32/sys-root/mingw/bin/debug-helper.exe.debug
   /usr/x86_64-w64-mingw32/sys-root/mingw/bin/remote-viewer.exe.debug
   /usr/x86_64-w64-mingw32/sys-root/mingw/bin/virt-viewer.exe.debug
   /usr/x86_64-w64-mingw32/sys-root/mingw/bin/windows-cmdline-wrapper.exe.debug
    Installed (but unpackaged) file(s) found:
   /usr/i686-w64-mingw32/sys-root/mingw/bin/debug-helper.exe.debug
   /usr/i686-w64-mingw32/sys-root/mingw/bin/remote-viewer.exe.debug
   /usr/i686-w64-mingw32/sys-root/mingw/bin/virt-viewer.exe.debug
   /usr/i686-w64-mingw32/sys-root/mingw/bin/windows-cmdline-wrapper.exe.debug
   /usr/x86_64-w64-mingw32/sys-root/mingw/bin/debug-helper.exe.debug
   /usr/x86_64-w64-mingw32/sys-root/mingw/bin/remote-viewer.exe.debug
   /usr/x86_64-w64-mingw32/sys-root/mingw/bin/virt-viewer.exe.debug
   /usr/x86_64-w64-mingw32/sys-root/mingw/bin/windows-cmdline-wrapper.exe.debug